Repository nilisha-jais/Musicophilia, pull requests merged in 2021-06, with the labels that each got.

#60 fixes issues-42
  style.css
Labels: LGMSOC21, 🟩 Level1

#74 made nav-bar sticky
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#90 Easy, medium, hard levels added in Memory Game
  Memory-game/choose.css
  Memory-game/choose.html
  Memory-game/easy.css
  Memory-game/easy.html
  Memory-game/easy.js
  Memory-game/hard.css
  Memory-game/hard.html
  Memory-game/hard.js
  Memory-game/images/card1.png
  Memory-game/images/card2.png
  Memory-game/images/card3.png
  Memory-game/images/card4.png
  Memory-game/images/card5.png
  Memory-game/images/card6.png
  Memory-game/images/cover.png
  Memory-game/medium.css
  Memory-game/medium.html
  Memory-game/medium.js
  index.html
Labels: LGMSOC21, 🟥 Level4

#80 feat: :mag: SEO Added
  index.html
Labels: LGMSOC21, 🟨 Level2

#81 fix: :zap: Eliminated extra space in the music cards
  musicBox/main.css
Labels: LGMSOC21, 🟩 Level1

#86 added favicon
  Band/index.html
  Memory-game/index.html
  Piano/index.html
  Quiz/index.html
  favicon.png
  index.html
  musicBox/index.html
Labels: LGMSOC21, 🟩 Level1

#87 Fixes Issue -63
  index.html
Labels: LGMSOC21, 🟩 Level1

#83 Issue #64 | Added animation to the icons
  Band/style.css
  index.html
Labels: LGMSOC21, 🟨 Level2

#93 Issue number #27 is solved. Readme file Updated
  README.md
Labels: LGMSOC21, 🟩 Level1

#100 Updated README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#120 Play band with keyboard
  Band/app.js
Labels: LGMSOC21, 🟨 Level2

#117 fix: :memo: Footer Copyrights notice updated
  index.html
Labels: LGMSOC21, 🟩 Level1

#118 fix: :bug: Fixed the header color
  Band/style.css
Labels: LGMSOC21, 🟩 Level1

#114 fix over flow of button and icon on mobile view #47
  index.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#106 Added contact-us page
  Contact-Us/contact.css
  Contact-Us/index.html
Labels: LGMSOC21, 🟥 Level4

#127 added Display of Social Media account issue #17
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#116 Issue 73
  artist/index.html
  artist/styles.css
  index.html
Labels: LGMSOC21, 🟥 Level4

#162 band page fitted in desktop size
  Band/index.html
  Band/style.css
Labels: LGMSOC21

#151 Added Dance Page using YouTube API
  Dance/index.html
  Dance/script.js
  Dance/style.css
  index.html
Labels: LGMSOC21

#144 made music quiz questions dynamic
  Quiz/index.html
  Quiz/script.js
Labels: LGMSOC21

#146 Common background for each level in the memory game
  Memory-game/choose.html
  Memory-game/easy.css
  Memory-game/hard.css
  Memory-game/medium.css
Labels: LGMSOC21

#163 Added Guess the Singer Game for Issue 40 in main repo
  Guess the Singers/index.html
  Guess the Singers/jscode.js
  Guess the Singers/pictures/alka.PNG
  Guess the Singers/pictures/ammy.PNG
  Guess the Singers/pictures/ar.PNG
  Guess the Singers/pictures/ariana.PNG
  Guess the Singers/pictures/arijit.PNG
  Guess the Singers/pictures/atif.PNG
  Guess the Singers/pictures/background2.gif
  Guess the Singers/pictures/beyonce.PNG
  Guess the Singers/pictures/billie.PNG
  Guess the Singers/pictures/bruno.PNG
  Guess the Singers/pictures/diljit.PNG
  Guess the Singers/pictures/ed.PNG
  Guess the Singers/pictures/eminem.PNG
  Guess the Singers/pictures/guru.PNG
  Guess the Singers/pictures/hardy.PNG
  Guess the Singers/pictures/jass.PNG
  Guess the Singers/pictures/jubin.PNG
  Guess the Singers/pictures/justin.PNG
  Guess the Singers/pictures/kaka.PNG
  Guess the Singers/pictures/kk.PNG
  Guess the Singers/pictures/mohit.PNG
  Guess the Singers/pictures/neha.PNG
  Guess the Singers/pictures/parmish.PNG
  Guess the Singers/pictures/praak.PNG
  Guess the Singers/pictures/rihanna.PNG
  Guess the Singers/pictures/selena.PNG
  Guess the Singers/pictures/sharry.PNG
  Guess the Singers/pictures/shreya.PNG
  Guess the Singers/pictures/siddhu.PNG
  Guess the Singers/pictures/sonu.PNG
  Guess the Singers/pictures/zyan.PNG
  Guess the Singers/stylesheet.css
Labels: LGMSOC21

#153 Update README.md
  README.md
Labels: LGMSOC21

#150 Update README.md
  README.md
Labels: LGMSOC21

#164 Added Hover Effect #161
  Band/style.css
Labels: LGMSOC21

#132 Improved the home page #2
  index.html
  music.png
  style.css
Labels: LGMSOC21

#174 UI changed #170
  Band/index.html
  Band/style.css
Labels: LGMSOC21

#172 Added custom scrollbar #133
  style.css
Labels: LGMSOC21

#175 Issue #97 Improvement in the UI of Band
  Band/index.html
  Band/style.css
  style.css
Labels: LGMSOC21

#177 Add issue #159 to main
  Contact-Us/contact.css
  Contact-Us/index.html
Labels: LGMSOC21

#185 alert added in music quiz
  Quiz/script.js
Labels: LGMSOC21

#189 Added new logo
  Logo/Logo-black.png
  Logo/Logo-white.png
  README.md
Labels: LGMSOC21

#183 Back option added in every game
  Band/button.css
  Band/index.html
  Dance/button.css
  Dance/index.html
  Memory-game/button.css
  Memory-game/choose.html
  Memory-game/easy.html
  Memory-game/hard.html
  Memory-game/medium.html
  Piano/button.css
  Piano/index.html
  Quiz/button.css
  Quiz/index.html
  artist/button.css
  artist/index.html
  musicBox/button.css
  musicBox/index.html
Labels: LGMSOC21

#182 Piano #176
  Piano/styles.css
Labels: LGMSOC21

#180 Added Hover Effects
  Band/style.css
Labels: LGMSOC21

#190 New Instrument Guitar Added(#108)
  Guitar/index.html
  Guitar/script.js
  Guitar/style.css
  index.html
Labels: LGMSOC21

#199 (fix): fixed the border size
  musicBox/main.css
Labels: LGMSOC21

#184 Added guess the singer game in main index file
  index.html
Labels: LGMSOC21

#201 Issue #194 Made Home Page Responsive
  Band/index.html
  Band/style.css
  style.css
Labels: LGMSOC21

#206 Changed the background of the quiz game .
  Quiz/background_img.png
  Quiz/style.css
Labels: LGMSOC21

#208 favicon changed
  favicon.png
Labels: LGMSOC21

#203 improved social media icons(#187)
  style.css
Labels: LGMSOC21

#212 Proper documentation and Indentation of code
  Band/app.js
  Band/button.css
  Band/index.html
  Band/style.css
  Contact-Us/contact.css
  Contact-Us/index.html
  Dance/button.css
  Dance/index.html
  Guess the Singers/index.html
  Guess the Singers/jscode.js
  Guitar/index.html
  Guitar/script.js
  Guitar/style.css
  Memory-game/app.js
  Memory-game/button.css
  Memory-game/choose.css
  Memory-game/choose.html
  Memory-game/easy.css
  Memory-game/easy.html
  Memory-game/easy.js
  Memory-game/hard.css
  Memory-game/hard.html
  Memory-game/hard.js
  Memory-game/index.html
  Memory-game/medium.css
  Memory-game/medium.html
  Memory-game/medium.js
  Memory-game/style.css
  Piano/index.html
  Piano/script.js
  Piano/styles.css
  Quiz/button.css
  Quiz/index.html
  Quiz/script.js
  Quiz/style.css
  artist/button.css
  artist/index.html
  artist/styles.css
  index.html
  musicBox/index.html
  musicBox/main.css
  musicBox/main.js
  style.css
Labels: LGMSOC21

#222 Navbar enhancement
  index.html
  style.css
Labels: LGMSOC21

#218 changed the position of badges
  README.md
Labels: LGMSOC21

#226 artist-page-update
  artist/index.html
Labels: LGMSOC21

#245 added tabla2
  index.html
  style.css
  tabla/img/tap1.png
  tabla/img/tap2.png
  tabla/index.css
  tabla/index.html
  tabla/index.js
  tabla/sound/d.mp3
  tabla/sound/t.mp3
Labels: LGMSOC21, 🟥 Level4

#241 issue solved
  README.md
Labels: LGMSOC21, 🟪 Level0

#235 Add issue #156 to main
  style.css
Labels: LGMSOC21, 🟪 Level0

#234 fixes issue-103 with glow effect in band context
  Band/index.html
  Band/style.css
Labels: LGMSOC21, 🟩 Level1

#251 added project admins section issue110
  README.md
Labels: LGMSOC21, 🟪 Level0

#232 worked issue #228 , needs follow up
  musicBox/button.css
  musicBox/index.html
  musicBox/main.css
  musicBox/main.js
Labels: LGMSOC21, 🟩 Level1

#263 about-page
  About/about.css
  About/index.html
  artist/index.html
  artist/styles.css
  index.html
Labels: LGMSOC21, 🟥 Level4

#260 Removed the Underline from the Back Button of quiz game
  Quiz/index.html
Labels: LGMSOC21, 🟪 Level0

#276 added score feature in Guess the Singer Page
  Guess the Singers/index.html
  Guess the Singers/jscode.js
  Guess the Singers/stylesheet.css
Labels: LGMSOC21, 🟩 Level1

#258 Made website Responsive
  index.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#278 Alert Pop up box feature in contact form successfully imported
  Contact-Us/index.html
Labels: LGMSOC21, 🟧 Level3

#295 Fixes issue-257
  Guess the Singers/stylesheet.css
Labels: LGMSOC21, 🟪 Level0

#294 Added "Back" button for Guitar, Tabla and Guess the Singer Page
  Guess the Singers/button.css
  Guess the Singers/index.html
  Guitar/button.css
  Guitar/index.html
  tabla/button.css
  tabla/index.css
  tabla/index.html
Labels: LGMSOC21, 🟨 Level2

#293 Fixes issue-256
  Guess the Singers/index.html
Labels: LGMSOC21, 🟪 Level0

#292 improved social media icons
  style.css
Labels: LGMSOC21, 🟪 Level0

#290 Piano keys
  Piano/button.css
  Piano/styles.css
Labels: LGMSOC21, 🟩 Level1

#285 Added contact us page in the website
  Contact-Us/contact.css
  Contact-Us/contact.html
  Contact-Us/index.html
  Contact-Us/logo-black.png
  index.html
Labels: LGMSOC21, 🟨 Level2

#274 Changed the UI of memory game page
  Memory-game/button.css
  Memory-game/choose.css
  Memory-game/choose.html
  Memory-game/images/2014-july-30-net-art-history-2.gif
Labels: LGMSOC21, 🟪 Level0

#229 Complete band
  Band/button.css
  Band/index.html
  Band/style.css
  contributing.md
Labels: LGMSOC21, 🟧 Level3

#304 Made navbar responsive
  Contact-Us/contact.css
  Contact-Us/contact.html
  Contact-Us/music.png
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#301 added metronome files
  .vscode/settings.json
  Metronome/assets/audio/click.wav
  Metronome/assets/images/favicon.png
  Metronome/assets/images/mute-icon.png
  Metronome/assets/images/unmute-icon.png
  Metronome/index.html
  Metronome/script.js
  Metronome/style.css
  index.html
Labels: LGMSOC21, 🟥 Level4

#300 Fix #296 Added automatic copyright upgradation
  index.html
Labels: LGMSOC21, 🟪 Level0

#303 Drum Kit Instrument
  drum/images/crash.png
  drum/images/kick.png
  drum/images/snare.png
  drum/images/tom1.png
  drum/images/tom2.png
  drum/images/tom3.png
  drum/images/tom4.png
  drum/index.html
  drum/index.js
  drum/sounds/crash.mp3
  drum/sounds/kick-bass.mp3
  drum/sounds/snare.mp3
  drum/sounds/tom-1.mp3
  drum/sounds/tom-2.mp3
  drum/sounds/tom-3.mp3
  drum/sounds/tom-4.mp3
  drum/styles.css
Labels: LGMSOC21, 🟧 Level3

#309 Added login page
  index.html
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟧 Level3

#310 added drum kit
  index.html
Labels: LGMSOC21, 🟪 Level0

#214 Update index.html
  index.html
Labels: LGMSOC21, 🟪 Level0

#313 Bug Resolved(Gif added)
  About/index.html
Labels: LGMSOC21

#314 contributing guide created.
  CONTRIBUTING-GUIDE.md
  contributing.md
  images/branch.png
  images/fork.png
  images/issue.png
  images/pullrequest.png
Labels: LGMSOC21, 🟩 Level1

#315 corrected positioning of back button and currected sound of tabla
  tabla/button.css
  tabla/index.css
  tabla/index.js
Labels: LGMSOC21, 🟪 Level0

#316 Issue No. #33 Time displayer added in Quiz game
  Quiz/index.html
  Quiz/script.js
  Quiz/style.css
Labels: LGMSOC21, 🟨 Level2

#323 Minor change in contribution guidelines
  README.md
Labels: LGMSOC21, 🟪 Level0

#326 Rishika1
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#334 Added Background Image in About and Login Page
  About/about.css
  login/login.css
Labels: LGMSOC21, 🟪 Level0

#330 Added dance category buttons to fetch and show related dance videos
  Dance/button.css
  Dance/index.html
  Dance/script.js
  Dance/style.css
Labels: LGMSOC21, 🟨 Level2

#336 added keypress
  tabla/button.css
  tabla/index.css
  tabla/index.html
  tabla/index.js
Labels: LGMSOC21, 🟩 Level1

#339 Added footer and navbar in about us
  About/about.css
  About/index.html
  About/music.png
  Contact-Us/contact.html
  drum/index.html
Labels: LGMSOC21, 🟩 Level1

#345 Updated UI of Login Page
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟧 Level3

#332 Rishika2
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#348 Login pages added in footer
  index.html
Labels: LGMSOC21, 🟪 Level0

#352 Alert Popup Feature on Contact Page successfully imported
  Contact-Us/contact.html
Labels: LGMSOC21, 🟩 Level1

#264 artistInfoFileUpdated
  artist/index.html
Labels: LGMSOC21, 🟩 Level1

#284 Added a theme changer button
  index.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#357 Added Favicon on all the pages
  About/index.html
  Contact-Us/contact.html
  Guess the Singers/index.html
  Memory-game/choose.html
  Memory-game/easy.html
  Memory-game/hard.html
  Memory-game/index.html
  Memory-game/medium.html
  Metronome/index.html
  artist/index.html
  drum/index.html
  login/login.html
Labels: LGMSOC21, 🟪 Level0

#361 Added Navbar in login Page
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#362 Images updated in Memory game
  Memory-game/hard.js
  Memory-game/images/card10.png
  Memory-game/images/card11.png
  Memory-game/images/card12.png
  Memory-game/images/card7.png
  Memory-game/images/card8.png
  Memory-game/images/card9.png
  Memory-game/medium.js
Labels: LGMSOC21

#356 nav bar and hamburger view changed
  About/index.html
  Contact-Us/contact.html
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#366 Fixed Navbar in Drum Kit
  drum/index.html
  drum/styles.css
Labels: LGMSOC21, 🟩 Level1

#371 PR against issue #291 || Changes in UI of Home Page
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#372 Dance-video cards with main video as popup onclick to card
  Dance/button.css
  Dance/index.html
  Dance/script.js
  Dance/style.css
Labels: LGMSOC21, 🟩 Level1

#370 Fixed typo "Mindfull" to "Mindful" and added UI features
  index.html
  login/login.css
Labels: LGMSOC21, 🟩 Level1

#382 UI and UX changes added in the guitar screen
  Guitar/background.jpg
  Guitar/index.html
  Guitar/style.css
Labels: LGMSOC21, 🟪 Level0

#380 bug removed
  index.html
Labels: LGMSOC21, 🟪 Level0

#379 Added question numbers to quiz questions
  Quiz/index.html
  Quiz/script.js
Labels: LGMSOC21, 🟩 Level1

#377 Added Lyrics finder link
  Lyrics_finder/index.html
  Lyrics_finder/script.js
  Lyrics_finder/style.css
  index.html
Labels: LGMSOC21, 🟥 Level4

#373 shown active page on nav bar
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#385 UI and UX changed, back button added
  drum/button.css
  drum/images/drum_background.jpg
  drum/index.html
  drum/styles.css
Labels: LGMSOC21, 🟩 Level1

#388 Chatbot Added
  index.html
Labels: LGMSOC21, 🟥 Level4

#390 Footer Improved
  style.css
Labels: LGMSOC21, 🟩 Level1

#398 Added pressing effect on buttons (#386)
  Band/app.js
  Band/index.html
  Band/style.css
Labels: LGMSOC21, 🟩 Level1

#392 Readjustment of contents of menubar in mobile view
  Contact-Us/contact.html
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#389 Flip card animation added
  index.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#410 forget password page
  ForgetPas/Forget.html
  ForgetPas/Questions-bro.svg
  login/login.html
Labels: LGMSOC21, 🟧 Level3

#406 Readjustment of content of about page in mobile view
  About/about.css
  About/index.html
Labels: LGMSOC21, 🟩 Level1

#409 Scroll to top button
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  Dance/index.html
  Dance/style.css
  artist/index.html
  artist/styles.css
  index.html
  main.js
  style.css
Labels: LGMSOC21, 🟩 Level1

#415 Making navigation bar visible in about page
  About/index.html
  Contact-Us/contact.html
  index.html
Labels: LGMSOC21, 🟪 Level0

#416 set responsiveness for lyrics finder
  Lyrics_finder/index.html
  Lyrics_finder/script.js
  Lyrics_finder/style.css
Labels: LGMSOC21, 🟪 Level0

#421 create bubbles fixed (#420)
  Band/app.js
Labels: LGMSOC21, 🟪 Level0

#427 Modified the css of login and sign up
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#418 Contact us page
  Contact-Us/contact.css
  Contact-Us/contact.html
Labels: LGMSOC21, 🟩 Level1

#431 Revamp ABout us Page and Home page issue #291
  About/about.css
  About/index.html
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#429 eye functionality in the password column
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#432 Bugs in cards of home page and about page fixed
  About/index.html
  index.html
Labels: LGMSOC21, 🟩 Level1

#437 login page correction (sign in and sign up sections were disintegrated) (#436)
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#438 Quotes added
  index.html
Labels: LGMSOC21, 🟩 Level1

#444 Made_guess_the_singer_page_responsive
  Guess the Singers/button.css
  Guess the Singers/index.html
  Guess the Singers/stylesheet.css
Labels: LGMSOC21, 🟩 Level1

#447 Made uniform navbars , footers and scroll bars for all pages
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  index.html
  login/login.css
  login/login.html
  style.css
Labels: LGMSOC21

#455 Added scale transform
  style.css
Labels: LGMSOC21, 🟪 Level0

#457 Octave extended
  Piano/button.css
  Piano/index.html
  Piano/notes/A.mp3
  Piano/notes/A4.wav
  Piano/notes/A5.wav
  Piano/notes/Ab.mp3
  Piano/notes/Ab4.wav
  Piano/notes/Ab5.wav
  Piano/notes/B.mp3
  Piano/notes/B4.wav
  Piano/notes/B5.wav
  Piano/notes/Bb.mp3
  Piano/notes/Bb4.wav
  Piano/notes/Bb5.wav
  Piano/notes/C.mp3
  Piano/notes/C4.wav
  Piano/notes/C5.wav
  Piano/notes/C6.wav
  Piano/notes/D.mp3
  Piano/notes/D4.wav
  Piano/notes/D5.wav
  Piano/notes/Db.mp3
  Piano/notes/Db4.wav
  Piano/notes/Db5.wav
  Piano/notes/E.mp3
  Piano/notes/E4.wav
  Piano/notes/E5.wav
  Piano/notes/Eb.mp3
  Piano/notes/Eb4.wav
  Piano/notes/Eb5.wav
  Piano/notes/F.mp3
  Piano/notes/F4.wav
  Piano/notes/F5.wav
  Piano/notes/G.mp3
  Piano/notes/G4.wav
  Piano/notes/G5.wav
  Piano/notes/Gb.mp3
  Piano/notes/Gb4.wav
  Piano/notes/Gb5.wav
  Piano/script.js
  Piano/styles.css
Labels: LGMSOC21, 🟨 Level2

#460 GooglePlusAndLogoProblemFixed
  .vscode/launch.json
  Thumbs.db
  login/login.css
Labels: LGMSOC21, 🟪 Level0

#461 Band page
  Band/app.js
  Band/button.css
  Band/images/Guitar1.png
  Band/images/Guitar3.png
  Band/images/flute.png
  Band/index.html
  Band/sounds/sound10.wav
  Band/sounds/sound11.wav
  Band/sounds/sound12.wav
  Band/sounds/sound7.wav
  Band/sounds/sound8.wav
  Band/sounds/sound9.wav
  Band/style.css
  style.css
Labels: LGMSOC21, 🟧 Level3

#462 miscellaneous changes
  About/about.css
  About/index.html
  Band/index.html
  Band/style.css
  Lyrics_finder/index.html
  Lyrics_finder/style.css
  about.html
  karaoke/css/style.css
  karaoke/index.html
Labels: LGMSOC21, 🟨 Level2

#446 Added tabla beats
  tabla/img/tap3.jpg
  tabla/img/tap4.jpg
  tabla/img/tap5.jpg
  tabla/index.css
  tabla/index.html
  tabla/index.js
  tabla/sound/u.m4a
  tabla/sound/w.m4a
  tabla/sound/y.m4a
Labels: LGMSOC21, 🟩 Level1
