Repository nilisha-jais/Musicophilia, pull requests merged in 2021-07, with the labels that each got.

#467 fixed navbar toggle issue #466
  About/index.html
  index.html
  login/login.html
Labels: LGMSOC21, 🟩 Level1

#465 Alignment Issue solved
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#468 Quotes added
  index.html
Labels: LGMSOC21, 🟪 Level0

#472 fixed card color and alignment issue
  About/about.css
  About/index.html
Labels: LGMSOC21, 🟩 Level1

#473 Aligned text in Rollick Games cards
  style.css
Labels: LGMSOC21, 🟪 Level0

#478 Updated Contact and Login page for mobile responsiveness
  Contact-Us/contact.css
  Contact-Us/contact.html
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟨 Level2

#480 Added transition to contact button
  Contact-Us/contact.html
Labels: LGMSOC21, 🟪 Level0

#483 input fields style changed
  Contact-Us/contact.css
Labels: LGMSOC21, 🟪 Level0

#368 issue #335 solved
  About/about.css
  About/dancing.gif
  About/index.html
  index.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#495 Changed font style and the horizontal rule line
  index.html
  style.css
Labels: LGMSOC21, 🟪 Level0

#497 Aligned about me heading evenly
  About/about.css
Labels: LGMSOC21, 🟪 Level0

#498 Flip Card animation added on the about us page
  About/about.css
  About/index.html
Labels: LGMSOC21, 🟨 Level2

#485 Improved spacing in all the pages
  login/login.css
  style.css
Labels: LGMSOC21, 🟪 Level0

#502 Modified Navbar and Toggle Button
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  index.html
  login/login.css
  login/login.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#503 added smooth scroll
  Dance/style.css
Labels: LGMSOC21, 🟪 Level0

#506 Changes in navbar.
  About/about.css
  Contact-Us/contact.css
  index.html
  login/login.css
  style.css
Labels: LGMSOC21, 🟨 Level2

#505 Changed the scrollbar for all pages to green color and added smooth behavior of scroll
  Contact-Us/contact.css
  login/login.css
  style.css
Labels: LGMSOC21, 🟪 Level0

#508 I have added hover on sign in button in login page.
  login/login.css
Labels: LGMSOC21, 🟪 Level0

#511 Changing navbar
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  index.html
  login/login.css
  login/login.html
  style.css
Labels: LGMSOC21, 🟪 Level0

#513 Improved scroll bar of various section inside home page and added smooth scroll behaviour
  Guess the Singers/stylesheet.css
  Lyrics_finder/style.css
  Quiz/style.css
  artist/styles.css
  drum/styles.css
  karaoke/css/style.css
  tabla/index.css
Labels: LGMSOC21, 🟩 Level1

#516 Fixed footers of contact and login page
  Contact-Us/contact.css
  Contact-Us/contact.html
  login/login.css
  login/login.html
Labels: LGMSOC21, 🟨 Level2

#519 Added space in footer of contact section
  Contact-Us/contact.html
Labels: LGMSOC21, 🟪 Level0

#520 🔧fixed navbar and fonts #518
  About/about.css
  About/index.html
  Contact-Us/contact.css
  Contact-Us/contact.html
  index.html
  login/login.css
  login/login.html
  style.css
Labels: LGMSOC21, 🟨 Level2

#523 added password validation in login page
  login/login.html
Labels: LGMSOC21, 🟪 Level0

#522 🔧fixed : logo redirect to homepage #521
  About/index.html
  Contact-Us/contact.html
  login/login.html
Labels: LGMSOC21, 🟪 Level0

#526 Theme switcher button updated
  index.html
Labels: LGMSOC21, 🟪 Level0

#528 updatedFile
  artist/index.html
  artist/searchArtist.js
  artist/styles.css
Labels: LGMSOC21, 🟨 Level2

#531 updated the footer properties
  About/about.css
Labels: LGMSOC21, 🟪 Level0

#532 added responsiveness to about page
  About/about.css
  About/index.html
Labels: LGMSOC21, 🟩 Level1

#535 updated placeholder
  Contact-Us/contact.html
Labels: LGMSOC21, 🟪 Level0

#534 Fixes #533 : fixed cardflip text mirroring on hover
  style.css
Labels: LGMSOC21, 🟪 Level0
